#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

# use scipy_packages.txt if Makefile create .scipy
[[ -e '/build/.scipy' ]] && packages_file=scipy_packages.txt || packages_file=packages.txt
echo "using $packages_file to determine packages"

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/${packages_file}
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler

#
# PIL library patch
#

for file in libjpeg.so libfreetype.so libz.so; do
  [[ -f /usr/lib/x86_64-linux-gnu/${file} ]] && ln -s /usr/lib/x86_64-linux-gnu/${file} /usr/lib
done

[[ -d /usr/include/freetype2 ]] && ln -s /usr/include/freetype2 /usr/include/freetype2/freetype

mkdir -p /usr/local/emr && \
	cd /usr/local/emr && \
	wget http://elasticmapreduce.s3.amazonaws.com/elastic-mapreduce-ruby.zip && \
	unzip elastic-mapreduce-ruby.zip
